import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { prisma } from '@/lib/prisma';

interface PopInfo {
  id: string;
  titulo: string;
  peso: number;
}

interface SetorReport {
  id: string;
  nome: string;
  pesoTotal: number;
  pesoAtingido: number;
  percentual: number;
  principaisPops: PopInfo[];
}

export default function RelatorioPage() {
  const [relatorio, setRelatorio] = useState<SetorReport[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/relatorio')
      .then(res => res.json())
      .then(data => {
        setRelatorio(data);
        setLoading(false);
      });
  }, []);

  const downloadPdf = () => {
    // Trigger download of PDF generated by server
    window.open('/api/relatorio/pdf', '_blank');
  };

  return (
    <div style={{ padding: '2rem', fontFamily: 'Inter, sans-serif', color: 'var(--text-main)' }}>
      <h1 style={{ marginBottom: '1rem' }}>Relatório de Metas por Setor</h1>
      {loading ? (
        <p>Carregando...</p>
      ) : (
        <table style={{ width: '100%', borderCollapse: 'collapse', background: 'var(--surface-2)', borderRadius: '8px', overflow: 'hidden' }}>
          <thead style={{ background: 'var(--surface-1)' }}>
            <tr>
              <th style={{ padding: '0.75rem', textAlign: 'left' }}>Setor</th>
              <th style={{ padding: '0.75rem', textAlign: 'right' }}>Percentual</th>
              <th style={{ padding: '0.75rem', textAlign: 'left' }}>Principais POPs</th>
            </tr>
          </thead>
          <tbody>
            {relatorio.map(setor => (
              <tr key={setor.id} style={{ borderBottom: '1px solid var(--border)' }}>
                <td style={{ padding: '0.75rem' }}>{setor.nome}</td>
                <td style={{ padding: '0.75rem', textAlign: 'right', color: setor.percentual >= 80 ? 'var(--success)' : 'var(--warning)' }}>
                  {setor.percentual.toFixed(1)}%
                </td>
                <td style={{ padding: '0.75rem' }}>
                  {setor.principaisPops.map(pop => (
                    <span key={pop.id} style={{ display: 'inline-block', marginRight: '0.5rem', background: 'rgba(255,255,255,0.1)', padding: '0.25rem 0.5rem', borderRadius: '4px' }}>
                      {pop.titulo} ({pop.peso})
                    </span>
                  ))}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <div style={{ marginTop: '2rem' }}>
        <button
          onClick={downloadPdf}
          style={{
            background: 'teal',
            color: 'white',
            padding: '0.75rem 1.5rem',
            border: 'none',
            borderRadius: '0.5rem',
            cursor: 'pointer',
            boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            transition: 'transform 0.2s'
          }}
          onMouseEnter={e => (e.currentTarget.style.transform = 'scale(1.05)')}
          onMouseLeave={e => (e.currentTarget.style.transform = 'scale(1)')}
        >
          Baixar PDF
        </button>
        <Link href="/admin" style={{ marginLeft: '1rem', color: 'var(--text-muted)' }}>
          ← Voltar ao painel
        </Link>
      </div>
    </div>
  );
}
